version: '3.8'

x-app: &app
  build:
    context: .
    target: hyku-base
    args:
      - HYKU_BULKRAX_ENABLED=true
  image: registry.gitlab.com/notch8/louisville-hyku:${TAG:-latest}
  env_file:
    - .env
  # NOTE: all common env variables moved to .env
  volumes:
    - HykuImports:/media/HykuImports
    - uploads:/app/samvera/hyrax-webapp/public/uploads:cached
    - assets:/app/samvera/hyrax-webapp/public/assets:cached
    - cache:/app/samvera/hyrax-webapp/tmp/cache:cached
    - .:/app/samvera/hyrax-webapp
  networks:
    internal:

volumes:
  assets:
  cache:
  db:
  fcrepo:
  redis:
  solr:
  uploads:
  uv:
  zk:
  zoo:
  HykuImports:
   driver_opts:
    type: "cifs"
    device: "//136.165.112.51/Groups/Digital/HykuImports"
    o: "addr=136.165.112.51,ro,cached"
    o: "uid=0,username=hyku,password=iuse4rchbtw!,file_mode=0777,dir_mode=0777"

networks:
  internal:

services:
  zoo:
    image: zookeeper:3.6.2
    ports:
      - 127.0.0.1:2181:2181
      - 127.0.0.1:7001:7000
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo:2888:3888;2181
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,srvr,ruok,conf
    volumes:
      - zoo:/data
      - zk:/datalog
    networks:
      internal:
    healthcheck:
      test: ["CMD-SHELL", "echo 'ruok' | nc -w 2 -q 2 localhost 2181 | grep imok || exit 1"]
      interval: "10s"
      timeout: "8s"

  solr:
    image: hyku/solr:8
    build:
      context: solr
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - OOM=script
      - VIRTUAL_PORT=8983
      - VIRTUAL_HOST=localhost
      - SOLR_OPTS=-Dsolr.jetty.request.header.size=65535
    user: root
    command: bash -c "
      chown -R 8983:8983 /var/solr
      && ./bin/solr zk cp file:/var/solr/data/security.json zk:/security.json
      && runuser -u solr -- solr-foreground"
    expose:
      - 8983
    ports:
      - 127.0.0.1:8983:8983
    volumes:
      - solr:/var/solr
      - /home/deploy/hyku/solr/security.json:/var/solr/data/security.json
      - /home/deploy/hyku/solr/limits.conf:/etc/security/limits.conf
      - /home/deploy/Backups/solr:/media/backups
    networks:
      internal:
    healthcheck:
      test: curl -sf http://$$SOLR_ADMIN_USER:$$SOLR_ADMIN_PASSWORD@localhost:8983/solr/admin/cores?action=STATUS || exit 1
      start_period: 10s
      interval: 20s
      timeout: 5s
      retries: 3
    depends_on:
      zoo:
        condition: service_healthy

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    volumes:
      - fcrepo:/data:cached
      - /home/deploy/Backups/fedora:/media/backups
    env_file:
      - .env
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=localhost
      - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"
    expose:
      - 8080
    ports:
      - 127.0.0.1:8080:8080
    networks:
      internal:

  db:
    image: postgres:11.1
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - VIRTUAL_PORT=5432
      - VIRTUAL_HOST=localhost
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  web:
    <<: *app
    # command: sh -l -c "bundle && yarn install && bundle exec puma -v -b tcp://0.0.0.0:3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=.${HYKU_ROOT_HOST}
      - TMPDIR=/app/samvera/hyrax-webapp/tmp/uploads
    depends_on:
      db:
        condition: service_started
      solr:
        condition: service_started
      fcrepo:
        condition: service_started
      redis:
        condition: service_started
      zoo:
        condition: service_started
      check_volumes:
        condition: service_started
      chrome:
        condition: service_started
      worker:
        condition: service_started
      initialize_app:
        condition: service_completed_successfully

    expose:
      - 3000
    ports:
      - 127.0.0.1:3000:3000

  worker:
    <<: *app
    build:
      context: .
      target: hyku-worker
      args:
        - HYKU_BULKRAX_ENABLED=true
      cache_from:
        - registry.gitlab.com/notch8/louisville-hyku:${TAG:-latest}
        - registry.gitlab.com/notch8/louisville-hyku/worker:${TAG:-latest}
    image: registry.gitlab.com/notch8/louisville-hyku/worker:${TAG:-latest}
    command: bash -l -c "bundle exec sidekiq"
    depends_on:
      check_volumes:
        condition: service_completed_successfully
      db:
        condition: service_started
      solr:
        condition: service_started
      fcrepo:
        condition: service_started
      redis:
        condition: service_started
      zoo:
        condition: service_started
      initialize_app:
        condition: service_completed_successfully



  # Do not recurse through all of tmp. derivitives will make booting
  # very slow and eventually just time out as data grows
  check_volumes:
    <<: *app
    user: root
    entrypoint: ["sh", "-x", "-c"]
    command:
      - >
        chown -R app:app /app/samvera/hyrax-webapp/public/uploads &&
        chown -R app:app /app/samvera/hyrax-webapp/public/assets &&
        chown -R app:app /app/samvera/hyrax-webapp/tmp/cache &&
        chown -R app:app /app/samvera/hyrax-webapp/db/schema.rb

  initialize_app:
    <<: *app
    environment:
      - CONFDIR=/app/samvera/hyrax-webapp/solr/config
    entrypoint: ["sh", "-c"]
    command:
      - >
        solrcloud-upload-configset.sh /app/samvera/hyrax-webapp/solr/config &&
        solrcloud-assign-configset.sh &&
        SOLR_COLLECTION_NAME=hydra-test solrcloud-assign-configset.sh &&
        db-migrate-seed.sh
    depends_on:
      db:
        condition: service_started
      solr:
        condition: service_healthy
      fcrepo:
        condition: service_started
      redis:
        condition: service_started

  redis:
    image: redis:5
    command: redis-server
    volumes:
      - redis:/data
    networks:
      internal:

  chrome:
    # password is 'secret'
    image: seleniarm/standalone-chromium:latest
    logging:
      driver: none
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 3G
    networks:
      internal:
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
      - VIRTUAL_PORT=7900
      - VIRTUAL_HOST=localhost
