# Hi - please dont edit this file directly, instead make changes in your .env file

login: &login
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'postgresql' %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] || Rails.application.credentials.dig(:production, :database_user) %>
  password: <%= ENV['DATABASE_PASSWORD'] || Rails.application.credentials.dig(:production, :database_password) %>
  database: <%= ENV['DATABASE_NAME'] || Rails.application.credentials.dig(:production, :database_name) %>
  pool: 50
  timeout: 5000


development:
  <<: *login
  username: <%= ENV['DATABASE_USER'] || Rails.application.credentials.dig(:development, :database_user) %>
  password: <%= ENV['DATABASE_PASSWORD'] || Rails.application.credentials.dig(:development, :database_password) %>
  database: <%= ENV['DATABASE_NAME'] || Rails.application.credentials.dig(:development, :database_name) %>

test:
  <<: *login
  database: <%= ENV['DATABASE_TEST_NAME'] || 'hyku_test' %>

staging:
  <<: *login


production:
  <<: *login
