development:
  user: Rails.application.credentials.dig(:development, :fedora_user)
  password: Rails.application.credentials.dig(:development, :fedora_password)
  url: <%= ENV['FEDORA_URL'] || Rails.application.credentials.dig(:development, :fedora_url) %>
  base_path: /prod
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_URL'] || "http://127.0.0.1:#{ENV.fetch('FCREPO_TEST_PORT', 8986)}/rest" %>
  base_path: /test
production:
  user: Rails.application.credentials.dig(:production, :fedora_user)
  password: Rails.application.credentials.dig(:production, :fedora_password)
  url: <%= ENV['FEDORA_URL'] || Rails.application.credentials.dig(:production, :fedora_url) %>
  base_path: /prod
  request: { timeout: 600, open_timeout: 60}
