development:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  password: <%= ENV['REDIS_PASSWORD'] || Rails.application.credentials.dig(:development, :redis_password) %>
test:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
production:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  password: <%= ENV['REDIS_PASSWORD'] || Rails.application.credentials.dig(:production, :redis_password) %>
