# This is a sample config file that points to a solr server for each environment
# TODO: there's also a Settings.solr.url configuration that is used in multitenant environments
development:
  url: <%= ENV['SOLR_URL'] || Rails.application.credentials.dig(:development, :solr_url) %>
test:
  url: <%= ENV['SOLR_URL'] ? ENV['SOLR_URL'] + 'hydra-test' : "http://127.0.0.1:#{ENV.fetch('SOLR_TEST_PORT', 8985)}/solr/hydra-test" %>
production:
  url: <%= ENV['SOLR_URL'] || Rails.application.credentials.dig(:production, :solr_url) %>
